# Generated by Django 3.1.6 on 2021-02-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210204_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='viewer',
            field=models.URLField(default='https://blabubaer.github.io/start-it-module1/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
